name: Build

on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  build:
    name: Build
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: gem install slather danger-slather
      - name: Build
        run: xcodebuild -scheme ButtonTapper -project ButtonTapper.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Test
        run: xcodebuild test -scheme ButtonTapperTests -project ButtonTapper.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Danger
        uses: danger/swift@3.3.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

