name: Build

on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  build:
    name: Build
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: gem install slather
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: ButtonTapper.xcodeproj
          scheme: ButtonTapperTests
          action: test
      - name: Check Code Coverage
        run: slather
        shell: bash 

