name: Build

on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  build:
    name: Build
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: gem install bundler -v 1.17.3 && bundle install
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: ButtonTapper.xcodeproj
          scheme: ButtonTapper
          destination: platform=iOS
          action: test
      - name: Check Code Coverage
        run: slather
        shell: bash 

